/* ============================================================
   CRT desktop OS — runs inside #crt-screen, shown when zoomed in
   ============================================================ */
(function () {
  /* ----------------------------------------------------------------
     Content is data-driven from data/profile.web.json (single source,
     generated by resume-engine). The literals below are only a FALLBACK
     used if the fetch fails — keep them lean. Bilingual fields arrive as
     { ko, en }; L() reads the current language with a graceful fallback.
     ---------------------------------------------------------------- */
  const FALLBACK_MODEL = {
    defaultLang: "ko",
    langs: ["ko"],
    ui: {},
    identity: { name: { ko: "홍예림", en: "YELIM HONG" }, sceneRole: "SOFTWARE ENGINEER", sceneTags: "backend · infra" },
    order: ["intro", "about", "stack", "contact"],
    apps: {
      intro: {
        glyph: "01", label: "Intro.txt", title: "intro.txt",
        body: `
        <div class="kicker">01 — Intro</div>
        <div class="h1">YELIM HONG<br><span class="dim" style="font-size:.62em;letter-spacing:.18em">홍예림</span></div>
        <p class="lead">복잡한 문제를 <span class="em">구조화</span>하고, 이를
        <span class="em">안정적인 시스템</span>으로 구현하는 백엔드 · 보안 엔지니어.</p>
        <hr>
        <div class="contact-row"><span class="k">Based</span><span>Seoul, Korea</span></div>
        <div class="contact-row"><span class="k">Status</span><span class="em">▸ open to work</span></div>
      `
      },
      about: {
        glyph: "02", label: "About.md", title: "about.md",
        body: `<div class="kicker">02 — About</div><div class="h1">기술의 원리부터<br>파고듭니다</div>`
      },
      stack: {
        glyph: "03", label: "Stack.cfg", title: "stack.cfg",
        body: `<div class="kicker">03 — Stack</div><div class="h1">도구 상자</div>`
      },
      contact: {
        glyph: "04", label: "Contact", title: "contact.exe",
        body: `<div class="kicker">04 — Contact</div><div class="big-cta">LET'S WORK<br>TOGETHER.</div>
        <div class="contact-row"><span class="k">GitHub</span><a href="https://github.com/hongyelim" target="_blank" rel="noopener">github.com/hongyelim</a></div>`
      }
    }
  };

  let MODEL = FALLBACK_MODEL;
  let currentLang = MODEL.defaultLang;

  // pick the current language from a bilingual field; plain strings pass through.
  function L(v, lang) {
    if (v == null) return "";
    if (typeof v === "string") return v;
    return v[lang] || v.ko || v.en || "";
  }

  // expose identity to scene.js idle labels (it falls back to its own strings if absent).
  function publishIdentity(identity) {
    if (!identity) return;
    window.__IDENTITY__ = {
      nameMain: L(identity.name, "en") || "YELIM HONG",
      sceneRole: identity.sceneRole || "SOFTWARE ENGINEER",
      sceneTags: identity.sceneTags || "backend · infra",
    };
  }
  publishIdentity(MODEL.identity);

  // Data sources, tried in order. The relative path works when the site serves
  // the repo as-is (local / GitHub Pages); on namo.site only js/ is served from
  // the jsDelivr CDN, so the relative fetch 404s and we fall through to the CDN
  // copy — without it the page silently renders the lean FALLBACK_MODEL.
  const DATA_URLS = [
    "data/profile.web.json",
    "https://cdn.jsdelivr.net/gh/AwesomeYelim/portfolio@master/data/profile.web.json",
  ];

  async function loadModel() {
    for (const url of DATA_URLS) {
      try {
        const r = await fetch(url, { cache: "no-cache" });
        if (!r.ok) continue;
        const d = await r.json();
        if (d && d.apps && d.order) return d;
      } catch { /* try the next source */ }
    }
    return null;
  }

  // load the single-source data; rebuild chrome if we're already mounted (race-safe).
  loadModel().then(d => {
    if (!d) return;                       // keep fallback
    MODEL = d;
    currentLang = d.defaultLang || currentLang;
    publishIdentity(d.identity);
    if (screen) buildChrome();
  });

  let screen = null, winLayer = null, taskItems = {}, zTop = 30, booted = false, clockTimer = null;
  const openWins = {}; // id -> win element

  function el(tag, cls, html) {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html != null) e.innerHTML = html;
    return e;
  }

  function mount(screenEl) {
    if (screen) return;
    screen = screenEl;
    buildChrome();
    if (!clockTimer) clockTimer = setInterval(clock, 1000 * 15);
  }

  // (re)build the static chrome — menubar, icons, taskbar — from MODEL.
  // Called on mount and again if data arrives after mount. The window layer
  // is created once and preserved across rebuilds.
  function buildChrome() {
    screen.querySelectorAll(".menubar, .icons, .taskbar").forEach(n => n.remove());
    taskItems = {};
    const order = MODEL.order || [];
    const showLang = MODEL.ui && MODEL.ui.langToggle && (MODEL.langs || []).length > 1;

    // menubar (+ language toggle on the right, before the clock)
    const mb = el("div", "menubar");
    const langItem = showLang
      ? `<span class="mb-item" id="mbLang">${MODEL.ui.langToggle[currentLang] || (currentLang === "ko" ? "EN" : "한국어")}</span>`
      : "";
    mb.innerHTML = `<span class="mb-logo">◆ YH/OS</span>
      <span class="mb-item">File</span><span class="mb-item">View</span><span class="mb-item">Help</span>
      <span class="mb-spacer"></span>${langItem}<span class="mb-clock" id="mbClock">--:--</span>`;
    screen.appendChild(mb);
    const lt = mb.querySelector("#mbLang");
    if (lt) lt.addEventListener("click", () => {
      window.__click && window.__click();
      setLang(currentLang === "ko" ? "en" : "ko");
    });

    // icons
    const icons = el("div", "icons");
    order.forEach(id => {
      const a = MODEL.apps[id]; if (!a) return;
      const ic = el("div", "icon");
      ic.dataset.app = id;
      ic.innerHTML = `<div class="icon-glyph">${a.glyph}</div><div class="icon-label">${L(a.label, currentLang)}</div>`;
      ic.addEventListener("click", () => { window.__click && window.__click(); selectIcon(ic); openWindow(id); });
      ic.addEventListener("dblclick", () => openWindow(id));
      icons.appendChild(ic);
    });
    screen.appendChild(icons);

    // window layer (create once, keep across rebuilds)
    if (!winLayer || !winLayer.isConnected) {
      winLayer = el("div", "win-layer");
      winLayer.style.cssText = "position:absolute;inset:0;z-index:20;pointer-events:none;";
    }
    screen.appendChild(winLayer);

    // taskbar
    const tb = el("div", "taskbar");
    let tasksHtml = "";
    order.forEach(id => { const a = MODEL.apps[id]; if (a) tasksHtml += `<span class="task" data-task="${id}">${a.title}</span>`; });
    tb.innerHTML = tasksHtml + `<span class="ts-sp"></span><span class="ts-net">▮▮▮ ONLINE</span>`;
    screen.appendChild(tb);
    tb.querySelectorAll(".task").forEach(t => {
      t.addEventListener("click", () => { window.__click && window.__click(); toggleWindow(t.dataset.task); });
      taskItems[t.dataset.task] = t;
      if (openWins[t.dataset.task]) t.classList.add("on");
    });

    clock();
  }

  // switch language: update toggle label, icon labels, and any open window body in place.
  function setLang(lang) {
    if (!(MODEL.langs || []).includes(lang)) return;
    currentLang = lang;
    const lt = document.getElementById("mbLang");
    if (lt && MODEL.ui && MODEL.ui.langToggle) lt.textContent = MODEL.ui.langToggle[lang] || (lang === "ko" ? "EN" : "한국어");
    screen && screen.querySelectorAll(".icon").forEach(ic => {
      const a = MODEL.apps[ic.dataset.app]; const lab = ic.querySelector(".icon-label");
      if (a && lab) lab.textContent = L(a.label, lang);
    });
    Object.keys(openWins).forEach(id => {
      const a = MODEL.apps[id], w = openWins[id];
      if (!a || !w) return;
      const body = w.querySelector(".win-body");
      if (body) body.innerHTML = L(a.body, lang);
    });
  }

  function clock() {
    const c = document.getElementById("mbClock");
    if (!c) return;
    const d = new Date();
    c.textContent = String(d.getHours()).padStart(2, "0") + ":" + String(d.getMinutes()).padStart(2, "0");
  }

  function selectIcon(ic) {
    screen.querySelectorAll(".icon").forEach(i => i.classList.remove("sel"));
    if (ic) ic.classList.add("sel");
  }

  function toggleWindow(id) { openWins[id] ? closeWindow(id) : openWindow(id); }

  function closeAllExcept(keepId) {
    Object.keys(openWins).forEach(k => {
      if (k === keepId) return;
      const w = openWins[k]; delete openWins[k];
      if (taskItems[k]) taskItems[k].classList.remove("on");
      if (w) w.remove();
    });
  }

  function openWindow(id) {
    const a = MODEL.apps[id];
    if (!a) return;
    if (openWins[id]) { focusWindow(id); return; }
    closeAllExcept();                       // single-window mode: only one open at a time
    selectIcon(screen.querySelector('.icon[data-app="' + id + '"]'));
    const w = el("div", "win");
    w.dataset.app = id;
    // unified placement so the window always sits neatly inside the screen, beside the icons
    w.style.left = "25%"; w.style.top = "11%";
    w.style.width = "71%"; w.style.maxHeight = "80%";
    w.innerHTML =
      `<div class="win-bar"><span class="win-title">${a.title}</span><span class="win-bar-sp"></span><span class="win-close">×</span></div>
       <div class="win-body">${L(a.body, currentLang)}</div>`;
    winLayer.appendChild(w);
    openWins[id] = w;
    if (taskItems[id]) taskItems[id].classList.add("on");
    w.querySelector(".win-close").addEventListener("click", e => { e.stopPropagation(); window.__click && window.__click(); closeWindow(id); });
    w.addEventListener("pointerdown", () => focusWindow(id));
    makeDraggable(w, w.querySelector(".win-bar"));
    focusWindow(id);
    // open animation
    w.animate(
      [{ transform: "scale(.9)", opacity: 0 }, { transform: "scale(1)", opacity: 1 }],
      { duration: 170, easing: "ease-out" }
    );
  }

  function closeWindow(id) {
    const w = openWins[id]; if (!w) return;
    delete openWins[id];
    if (taskItems[id]) taskItems[id].classList.remove("on");
    w.animate([{ opacity: 1 }, { opacity: 0, transform: "scale(.95)" }], { duration: 130, easing: "ease-in" })
      .onfinish = () => w.remove();
  }

  function focusWindow(id) {
    const w = openWins[id]; if (!w) return;
    Object.values(openWins).forEach(x => x.classList.remove("front"));
    w.classList.add("front");
    w.style.zIndex = ++zTop;
  }

  function makeDraggable(win, handle) {
    let sx, sy, ox, oy, rect, parent;
    handle.addEventListener("pointerdown", e => {
      if (e.target.classList.contains("win-close")) return;
      e.preventDefault();
      parent = screen.getBoundingClientRect();
      rect = win.getBoundingClientRect();
      sx = e.clientX; sy = e.clientY;
      ox = rect.left - parent.left; oy = rect.top - parent.top;
      handle.setPointerCapture(e.pointerId);
      const move = ev => {
        let nx = ox + (ev.clientX - sx);
        let ny = oy + (ev.clientY - sy);
        nx = Math.max(-rect.width * 0.4, Math.min(nx, parent.width - rect.width * 0.6));
        ny = Math.max(parent.height * 0.07, Math.min(ny, parent.height - 28));
        win.style.left = (nx / parent.width * 100) + "%";
        win.style.top = (ny / parent.height * 100) + "%";
      };
      const up = ev => {
        handle.releasePointerCapture(e.pointerId);
        handle.removeEventListener("pointermove", move);
        handle.removeEventListener("pointerup", up);
      };
      handle.addEventListener("pointermove", move);
      handle.addEventListener("pointerup", up);
    });
  }

  /* ---------- boot sequence ---------- */
  const BOOT_LINES = [
    ["YH/OS v2.6   (c) 1986 YELIM HONG SYSTEMS", ""],
    ["MEMORY TEST ......................... ", "OK"],
    ["MOUNT /dev/portfolio ................ ", "OK"],
    ["LOAD backend.module ................. ", "OK"],
    ["LOAD infra.daemon ................... ", "OK"],
    ["INIT automation.pipeline ............ ", "OK"],
    ["", ""],
    ["READY.", ""]
  ];

  function boot(onDone) {
    if (booted) { if (onDone) onDone(); return; }
    const b = el("div", "boot");
    screen.appendChild(b);
    let li = 0, buf = "";
    function nextLine() {
      if (li >= BOOT_LINES.length) {
        booted = true;
        setTimeout(() => {
          b.animate([{ opacity: 1 }, { opacity: 0 }], { duration: 280 }).onfinish = () => b.remove();
          selectIcon(screen.querySelector('.icon[data-app="intro"]'));
          openWindow("intro");
          if (onDone) onDone();
        }, 380);
        return;
      }
      const [pre, ok] = BOOT_LINES[li];
      buf += pre + (ok ? `<span class="ok">${ok}</span>` : "") + "\n";
      b.innerHTML = buf + '<span class="cur"></span>';
      li++;
      setTimeout(nextLine, pre === "" ? 90 : 150);
    }
    nextLine();
  }

  window.Desktop = { mount, boot, openWindow, setLang, getLang: () => currentLang, isBooted: () => booted };
})();
